### ISSUE TITLE
Version problems

### ISSUE THREAD

**Issue by p-mckenna** [leeassam/pi-bootcamp#1]
Hi Lee,
I am just following your online course, Raspberry Pi Bootcamp : For the Beginner, and I am having problems with the sample code for blinkLED. It seems some of the commands have changed since this tutorial was written.
I have needed to change 2 things so far:
Print is now a function, so it needs to have brackets around whatever is being printed.
was  print "Iteration " + str(i+1)
now  print ("Iteration " + str(i+1))
 
raw_input has been renamed to just input

Thanks,
Pat

P.S. I just noticed in your tutorial, that you selected version python version 2. Unfortunately, when I downloaded Raspbian, it did not include version 2. The only version it came with is version 3, so I only had 1 choice.

**Comment by leeassam** [comment]
Thanks for pointing this out. I changed the print functions to the python3 format so that others will not have this problem.
